### ISSUE TITLE
API 2.0 authentication

### ISSUE THREAD

**Issue by axlroden** [Anthony25/python-netboxapi#1]
Are you going to upgrade the code for Token authentication ? :)

**Comment by Anthony25** [comment]
Hi,
Yes, sorry, I didn't have upgraded this module for Netbox 2.0 yet. Thanks for the request, I'll to do it today.

**Comment by Anthony25** [comment]
Fixed in 18358db8e879351c11ba868590fe3eec1f8de65e

**Comment by Anthony25** [comment]
As it is related, and also because I wrote about it here, I am adding POST/PUT/DELETE methods to this client API for a complete compatibility with netbox 2.0.

It is currently in the netbox2.0 branch. POST and DELETE have been implementing, and I am adding the PUT method. I don't know if PATCH will be implemented, as it does not really reflect the "ORM like" logic I try to follow.

**Comment by axlroden** [comment]
I've used post and patch before this with your api ?

**Comment by Anthony25** [comment]
No, but I said I was going to upgrade this module for Netbox 2.0, and did only partially. I just added the token authentication, but now it will be fully compatible with all changed done to the API.
